language: python
python:
  - "2.7"

# Install dependencies
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-tk
install: pip install -r requirements.pip --use-mirrors

# Whitelist
#branches:
#  only:
#    - develop

# Command to run tests
script:
  - cd software/openvisualizer/
  - scons unittests
  - scons docs